name: Main branch regression tests
run-name: Running nightly regression Tests
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0/5 * * * 1-5'

jobs:
  Smoke-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup Chrome Browser and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Run Nightly Regression Tests in headless Chrome
        run: mvn test -Dbrowser=chromeheadless

      - name: Nightly Regression
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Report File
          path: target/cucumber-report/report.html
 newbranch


 main
