name: Main branch smoke tests cross-browser  11
run-name: Running Smoke Tests  11
on:
  push:
    branches:
      - main
jobs:
  Smoke-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup Chrome Browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'


      - name: Run Smoke Tests in headless Chrome
        run: mvn test -D cucumber.filter.tags="@smoke" -Dbrowser=chromeheadless



      - name: Generate Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Report File
          path: target/cucumber-report/*.html
